#!/bin/bash
# One-shot Wi-Fi AP provisioning for the Winmate GCS (built-in radio on usb0).
#
# Ties together the device-specific / secret bits that are intentionally NOT in
# git, then runs the project's own setup_wifi_ap.sh (which installs the AP tray,
# systemd units and NAT). Safe on Winmate: RADIO_BUILTIN=1 keeps eth0 as WAN.
#
# Secrets are never stored in the repo. Provide the AP passphrase via prompt or:
#   sudo AP_SSID=caimanHD AP_PASS='********' ./scripts/provision-ap-winmate.sh
#
# Run as root.
set -euo pipefail

if [[ "${EUID}" -ne 0 ]]; then
    echo "Run as root: sudo $0" >&2
    exit 1
fi

PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

AP_SSID="${AP_SSID:-caimanHD}"
AP_CHANNEL="${AP_CHANNEL:-6}"
AP_HW_MODE="${AP_HW_MODE:-g}"
AP_COUNTRY="${AP_COUNTRY:-DE}"
HOSTAPD_CONF="/etc/hostapd/drone-hotspot.conf"
STREAMING_CONF="/etc/default/gcs-ap-streaming"

log() { echo "[provision-ap] $*"; }

# --- AP passphrase (never from git) ----------------------------------------
if [[ -z "${AP_PASS:-}" ]]; then
    read -r -s -p "[provision-ap] WPA2 passphrase for '${AP_SSID}' (>=8 chars): " AP_PASS
    echo
fi
if [[ ${#AP_PASS} -lt 8 || ${#AP_PASS} -gt 63 ]]; then
    echo "ERROR: WPA2 passphrase must be 8..63 characters" >&2
    exit 1
fi

# --- 1. Packages ------------------------------------------------------------
missing=()
command -v hostapd >/dev/null || missing+=(hostapd)
command -v iw >/dev/null || missing+=(iw)
# Full dnsmasq package (not just dnsmasq-base) — provides dnsmasq.service that
# drone-hotspot.service starts. dnsmasq-base only ships the binary (used by NM).
dpkg -s dnsmasq >/dev/null 2>&1 || missing+=(dnsmasq)
# GObject binding required by the AP tray (gcs-ap-tray.py: AyatanaAppIndicator3).
dpkg -s gir1.2-ayatanaappindicator3-0.1 >/dev/null 2>&1 \
    || missing+=(gir1.2-ayatanaappindicator3-0.1)
# GStreamer plugins for QGC's local UDP H.264 video pane:
#   plugins-bad -> h264parse   libav -> avdec_h264   qt5 -> qmlglsink (Qt5 sink)
# Without these the QGC video pipeline silently fails to start (phone RTSP is
# unaffected — that path is decoded by ffmpeg, not QGC's GStreamer).
dpkg -s gstreamer1.0-plugins-bad >/dev/null 2>&1 || missing+=(gstreamer1.0-plugins-bad)
dpkg -s gstreamer1.0-libav >/dev/null 2>&1 || missing+=(gstreamer1.0-libav)
dpkg -s gstreamer1.0-qt5 >/dev/null 2>&1 || missing+=(gstreamer1.0-qt5)
if ((${#missing[@]})); then
    log "Installing: ${missing[*]}"
    apt-get update -y
    DEBIAN_FRONTEND=noninteractive apt-get install -y "${missing[@]}"
fi

# --- 2. Streaming config with Winmate interface roles -----------------------
if [[ -f "$STREAMING_CONF" ]] && ! grep -q '^RADIO_BUILTIN=1' "$STREAMING_CONF"; then
    cp -a "$STREAMING_CONF" "${STREAMING_CONF}.bak.$(date +%s)"
    log "Backed up existing $STREAMING_CONF"
fi
install -m 644 "$PROJECT_DIR/config/gcs-ap-streaming.winmate.conf" "$STREAMING_CONF"
log "Installed $STREAMING_CONF (RADIO_IF=usb0, RADIO_BUILTIN=1, INTERNET_IFS from WAN)"

# --- 3. hostapd AP config (secret, 0600) ------------------------------------
mkdir -p /etc/hostapd
umask 077
cat > "$HOSTAPD_CONF" <<EOF
# Winmate GCS AP — generated by provision-ap-winmate.sh (not in git)
interface=uap0
driver=nl80211
ssid=${AP_SSID}
country_code=${AP_COUNTRY}
hw_mode=${AP_HW_MODE}
channel=${AP_CHANNEL}
ieee80211n=1
wmm_enabled=1
auth_algs=1
wpa=2
wpa_key_mgmt=WPA-PSK
rsn_pairwise=CCMP
wpa_passphrase=${AP_PASS}
beacon_int=100
EOF
chmod 600 "$HOSTAPD_CONF"
umask 022
log "Wrote $HOSTAPD_CONF (SSID=${AP_SSID}, channel=${AP_CHANNEL})"

# --- 4. Point hostapd at our config, unmask service -------------------------
if [[ -f /etc/default/hostapd ]]; then
    if grep -q '^[#]*DAEMON_CONF=' /etc/default/hostapd; then
        sed -i "s|^[#]*DAEMON_CONF=.*|DAEMON_CONF=\"$HOSTAPD_CONF\"|" /etc/default/hostapd
    else
        echo "DAEMON_CONF=\"$HOSTAPD_CONF\"" >> /etc/default/hostapd
    fi
else
    echo "DAEMON_CONF=\"$HOSTAPD_CONF\"" > /etc/default/hostapd
fi
systemctl unmask hostapd 2>/dev/null || true
"$PROJECT_DIR/scripts/ensure-hostapd-concurrent.sh" 2>/dev/null || true
log "hostapd DAEMON_CONF set, service unmasked"

# --- 5. Run the project's AP installer (tray + units + NAT) ------------------
log "Running project setup_wifi_ap.sh ..."
"$PROJECT_DIR/setup_wifi_ap.sh"

# --- 6. GCS user services (MAVProxy + widget + AP unicast fan-out) -----------
# Installs/enables mavproxy-gcs, mav-widget and mav-ap-fanout for the desktop
# user. The fan-out relay unicasts MAVLink telemetry to every AP client
# (phones) — reliable for many clients, unlike udpbcast.
log "Running project setup_autostart.sh (MAVProxy + widget + AP fan-out) ..."
"$PROJECT_DIR/setup_autostart.sh"

log "Done. AP is installed and OFF by default."
log "Turn on:  toggle-ap.sh   (or the top-panel tray icon)"
log "Verify:   check-gcs-link.sh ; check-ap-stream.sh ; check-nat.sh"
