#!/bin/bash
# Pin interface names (eth0=radio, eth1=USB-debug) and restore static 192.168.53.1 on eth0.
# Radio adapter is now USB — MAC is auto-detected at install time (portable across machines).

set -euo pipefail

if [[ "${EUID}" -ne 0 ]]; then
    echo "Run as root: sudo $0" >&2
    exit 1
fi

if [[ -n "${MAV_WIDGET_DIR:-}" ]]; then
    PROJECT_DIR="${MAV_WIDGET_DIR}"
else
    PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
fi
if [[ ! -d "${PROJECT_DIR}/config" && -d /home/ubuntu/MAV_widget/config ]]; then
    PROJECT_DIR=/home/ubuntu/MAV_widget
fi
if [[ ! -d "${PROJECT_DIR}/config" ]]; then
    echo "Config not found — set MAV_WIDGET_DIR=/path/to/MAV_widget" >&2
    exit 1
fi
CONFIG="${PROJECT_DIR}/config"

log() { echo "[setup-network] $*"; }

# ---------------------------------------------------------------------------
# Auto-detect the radio USB-ETH adapter.
#
# Override via env:  RADIO_ETH_IFACE=enx001122334455  sudo ./setup_network.sh
# The debug USB adapter MAC is known and stable — we exclude it so the radio
# adapter is the only candidate on most machines.
# ---------------------------------------------------------------------------
DEBUG_MAC="00:60:6e:b9:ce:28"

detect_radio_iface() {
    local candidates=()
    for iface in $(ls /sys/class/net/); do
        # Must have a device (skip loopback, tun, veth…)
        [[ -e "/sys/class/net/$iface/device" ]] || continue
        # Skip wireless
        [[ -d "/sys/class/net/$iface/wireless" ]] && continue
        local mac
        mac=$(cat "/sys/class/net/$iface/address" 2>/dev/null || true)
        [[ -z "$mac" ]] && continue
        # Skip the known debug adapter
        [[ "${mac,,}" == "${DEBUG_MAC,,}" ]] && continue
        candidates+=("$iface")
    done

    case ${#candidates[@]} in
        0)
            echo "" ; return 1 ;;
        1)
            echo "${candidates[0]}" ; return 0 ;;
        *)
            log "Multiple ETH adapters found (excluding debug adapter):"
            for i in "${!candidates[@]}"; do
                local m
                m=$(cat "/sys/class/net/${candidates[$i]}/address" 2>/dev/null || true)
                log "  $((i+1)). ${candidates[$i]}  MAC=$m"
            done
            if [[ -t 0 ]]; then
                read -r -p "[setup-network] Select radio adapter number [1]: " choice
                choice=${choice:-1}
            else
                log "Non-interactive mode — selecting first adapter."
                choice=1
            fi
            echo "${candidates[$((choice-1))]}" ; return 0 ;;
    esac
}

# Use explicit env override or auto-detect
if [[ -n "${RADIO_ETH_IFACE:-}" ]]; then
    RADIO_IFACE="$RADIO_ETH_IFACE"
    log "Using adapter from environment variable: $RADIO_IFACE"
else
    RADIO_IFACE=$(detect_radio_iface || true)
fi

if [[ -z "$RADIO_IFACE" ]]; then
    log "ERROR: radio ETH adapter not found. Plug in the USB adapter and retry." >&2
    exit 1
fi

RADIO_MAC=$(cat "/sys/class/net/$RADIO_IFACE/address" 2>/dev/null || true)
if [[ -z "$RADIO_MAC" ]]; then
    log "ERROR: could not read MAC of interface $RADIO_IFACE" >&2
    exit 1
fi

log "Radio adapter: $RADIO_IFACE  MAC=$RADIO_MAC"

# ---------------------------------------------------------------------------
# Generate .link file with the detected MAC (overwrites repo template)
# ---------------------------------------------------------------------------
RADIO_LINK_CONTENT="# Radio USB-ETH adapter -> always eth0
# Generated by setup_network.sh on $(date -I) — do not edit manually.
[Match]
MACAddress=${RADIO_MAC}
Type=ether

[Link]
Name=eth0
"

log "Installing systemd .link rules (MAC -> eth0/eth1)..."
printf '%s' "$RADIO_LINK_CONTENT" > /etc/systemd/network/10-gcs-builtin.link
chmod 644 /etc/systemd/network/10-gcs-builtin.link
install -m 644 "${CONFIG}/20-gcs-usb.link" /etc/systemd/network/20-gcs-usb.link
# udev NAME= rules conflict with systemd.link — remove if present.
rm -f /etc/udev/rules.d/70-gcs-net-names.rules
udevadm control --reload-rules 2>/dev/null || true

log "NetworkManager: no auto-default on eth0/eth1..."
install -m 644 "${CONFIG}/NetworkManager-gcs.conf" \
    /etc/NetworkManager/conf.d/gcs-no-auto-default.conf

log "Disabling cloud-init network overwrite..."
install -m 644 "${CONFIG}/99-disable-cloud-init-network.cfg" \
    /etc/cloud/cloud.cfg.d/99-disable-cloud-init-network.cfg

# Generate GCS-Radio NM profile with the detected MAC
log "Generating NetworkManager profile GCS-Radio (MAC=$RADIO_MAC)..."
cat > /etc/NetworkManager/system-connections/GCS-Radio.nmconnection << EOF
[connection]
id=GCS-Radio
uuid=2f3b5aeb-bc73-3a2c-8cd8-8a79935a0f8e
type=ethernet
interface-name=eth0
autoconnect=true
autoconnect-priority=100

[ethernet]
mac-address=${RADIO_MAC^^}

[ipv4]
method=manual
address1=192.168.53.1/24
never-default=true

[ipv6]
method=disabled
EOF
chmod 600 /etc/NetworkManager/system-connections/GCS-Radio.nmconnection

log "Installing NetworkManager profiles..."
install -m 600 "${CONFIG}/gcs-eth1-usb.nmconnection" \
    /etc/NetworkManager/system-connections/USB-Debug.nmconnection
chown root:root /etc/NetworkManager/system-connections/GCS-Radio.nmconnection \
    /etc/NetworkManager/system-connections/USB-Debug.nmconnection

install -m 755 "${PROJECT_DIR}/scripts/ensure_network.sh" /usr/local/bin/ensure-network.sh

sed "s|__PROJECT_DIR__|${PROJECT_DIR}|g" \
    "${PROJECT_DIR}/systemd/gcs-network.service" > /etc/systemd/system/gcs-network.service

while IFS= read -r name; do
    [[ -z "$name" ]] && continue
    nmcli connection delete "$name" 2>/dev/null || true
    log "Removed profile: $name"
done < <(nmcli -t -f NAME connection show | grep -E '^Wired connection ' || true)

systemctl daemon-reload
systemctl enable gcs-network.service

log "Applying network now (swap names if needed)..."
/usr/local/bin/ensure-network.sh

log "Done. Reboot once so systemd .link rules apply at early boot."
"${PROJECT_DIR}/scripts/check-network.sh" || true
